### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by mav2287**
@oscarotero sorry for the delay on this, between work, Easter and my wife making torrijas for me I got a bit behind.

I tried to follow all the same conventions as the other middleware repos and also wrote the appropriate unit tests. Please spot check my work and let me know if I missed anything.

### CODE REVIEW

**Comment by oscarotero** [comment]
Torrijas? I love them!!

Thanks for this, it looks great. The only thing is, like in https://github.com/middlewares/base-path/pull/3#issuecomment-815313799, the function to define an attribute name shouldn't have a default value because the function without any argument (`$lowercase->attribute()`) is not clear enough.

**Comment by mav2287** [comment]
Me too! It's impossible to find the right bread here in Kansas and my wife got frustrated with what she could find so she made her own this year. They were amazing!

I'm a big fan of having defaults set, but I see your point. I updated the class, test and read me. Let me know if you see anything else in the commit I may have overlooked.

**Comment by oscarotero** [comment]
It's great. Thank you. I'm going to add you as a colaborator of this repo, so you can commit directly to it.

**Comment by mav2287** [comment]
Awesome thanks @oscarotero

**Pull request merged**
